### ISSUE TITLE
Clicking on menu item results in freeze when in full-screen mode.

### ISSUE THREAD

**Issue by sohocoke** [bigbearlabs/webbuddy-support#109]
Due to regression with anchor window management.

```
2014-03-14 14:52:46.468 WebBuddy[881:303] spaces.rb:121:in `update_current_anchor_window': anchor window unavailable for space! (RuntimeError)
    from spaces.rb:41:in `current_space_id'
    from WebBuddyAppDelegate.rb:523:in `current_viewer_wc'
    from WebBuddyAppDelegate.rb:480:in `activate_viewer_window:'
    from hotkey.rb:81:in `hotkey_action_activate_viewer_window:'
    from hotkey.rb:115:in `on_double_tap:'
    from hotkey.rb:49:in `block in hotkey_enabled:'
    from hotkey.rb:312:in `react_to_modkey'
    from hotkey.rb:248:in `block in init_modkey_reactions'
    from reactive.rb:13:in `block in react_to:'
    from kvo.rb:96:in `block in observeValueForKeyPath:ofObject:change:context:'
    from kvo.rb:93:in `observeValueForKeyPath:ofObject:change:context:'
    from kvc.rb:54:in `kvc_set:'
    from kvc.rb:59:in `kvc_set_if_needed:'
    from hotkey.rb:368:in `on_nsevent:'
    from hotkey.rb:266:in `block in add_modkey_action_definition:'
```

**Comment by sohocoke** [comment]
Triggers #111.

**Comment by sohocoke** [comment]
Cause is the combination of changing UI agent mode to false, and existing anchor window behaviour.

**Comment by sohocoke** [comment]
Tactical resolution: revert app to UIAgent. 

Strategic resolution: unsure as of yet.

**Comment by sohocoke** [comment]
#129 will allow us to revert back to UIAgent = false and still work with full screen mode.

Until then, the issue is resolved after reverting got UIAgent.
