### ISSUE TITLE
hotkey registration fails

### ISSUE THREAD

**Issue by sohocoke** [bigbearlabs/webbuddy-support#32]

**Comment by sohocoke** [comment]
```
2013-01-16 15:01:22.876 WebBuddy-interactive[60218:707] ## WARNING ##: ** Error! #<NoMethodError: undefined method `[]' for nil:NilClass> while trying #<Proc:0x402048d60> ** backtrace: WebBuddyAppDelegate.rb:641:in `update_toggle_menu_item'
WebBuddyAppDelegate.rb:67:in `block'
PERubyUtil.rb:16:in `try'
WebBuddyAppDelegate.rb:57:in `finish_start_panel'
WebBuddyAppDelegate.rb:231:in `performWebkitInvokableOperation'
rb_main.rb:37:in `<main>'
```

**Comment by sohocoke** [comment]
status: obsolete
